apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: otel-demo
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: otel-demo
  source:
    repoURL: https://open-telemetry.github.io/opentelemetry-helm-charts
    chart: opentelemetry-demo
    targetRevision: 0.32.7
    helm:
      values: |
        grafana:
          enabled: false
          persistence:
            enabled: false
        components:
          frontend:
            envOverrides:
              - name: FRONTEND_ADDR
                value: "0.0.0.0:8080"
            resources:
              limits:
                memory: 512Mi
              requests:
                memory: 256Mi
          product-catalog:
            resources:
              limits:
                memory: 128Mi  # Set >= requests
              requests:
                memory: 128Mi
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
