apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: otel-demo
  namespace: argocd
spec:
  source:
    repoURL: https://github.com/open-telemetry/opentelemetry-demo.git
    targetRevision: main
    path: charts/opentelemetry-demo
    helm:
      values: |
        grafana:
          # make sure we don't try to mount dashboards
          dashboardsEnabled: false
          sidecar:
            dashboards:
              enabled: false
          persistence:
            enabled: false
        components:
          loadGenerator: false
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
